### ISSUE TITLE
Investigate enabling ACL per jenkins job while keeping the authentication strategy to Github

### ISSUE THREAD

**Issue by sthaha** [fabric8io/fabric8-build-team#14] opened 2018-01-08 08:44 UTC
Currently it doesn't seem like there is a way to allow a subset of developers to administrate only certain jobs. E.g. if we want to grand the permission to kill some jobs we will have to give them the admin rights.

The goal of the task is to allow developers to administrate only a subset of the jobs so that builds can be stopped/restarted.

**Comment by pradeepto** [comment] 2018-01-08 08:52
@sthaha isn't this a duplicate of https://github.com/fabric8io/fabric8-build-team/issues/5  ?

cc @rupalibehera @chmouel

**Comment by rupalibehera** [comment] 2018-01-08 08:58
@sthaha, I am already working on this one.

**Comment by chmouel** [comment] 2018-01-08 09:30
This is a different issue, compared to #5 here we want something more specific : 

* We want to be able to allow set of developers admins of some jobs

There is no way currently to  allow a set of developers being admin of only certain jobs,

For example if we want to give them the ability to kill some jobs we need to give them a full access.

We want to be able to give them admin only to some jobs.

#5 is more generic and documentation compared to this,

@sthaha  can you update this task with the description, please.

**Comment by sthaha** [comment] 2018-01-15 01:59
### Status update

@rupalibehera and I have been investigating the authorisation mechanism that is currently in place and I think what we currently have should suffice the requirement.

The current authorisation allows any member of the `orgs` listed in the jenkins config who has push right (belongs to `committer` group) to the git repo to cancel a build and this seems fair to me.

Thanks to @rupalibehera  for the help

**Comment by pranavgore09** [comment] 2018-01-15 12:56
@chmouel @sthaha 

GH ids -
Pranav: pranavgore09
Deb: debloper

**Comment by sthaha** [comment] 2018-01-15 13:03
@pranavgore09 could you please point me to a jenkins job or PR to the github repo  that you may want to kill?

**Comment by pranavgore09** [comment] 2018-01-15 13:36
@sthaha following two jobs

fabric8-planner
 CI  - https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-planner/
 repo - https://github.com/fabric8-ui/fabric8-planner/

fabric8-wit (dropping this part as of now)
~~CI - https://jenkins.cd.test.fabric8.io/job/fabric8-services/job/fabric8-wit/~~
~~repo - https://github.com/fabric8-services/fabric8-wit/~~

**Comment by sthaha** [comment] 2018-01-18 13:53
### Status Update

@chmouel 
After a bit more digging into the [github-auth docs](https://wiki.jenkins.io/display/JENKINS/Github+OAuth+Plugin#GitHubOAuthPlugin-AuthorizationinGlobalSecurity.), my proposal is to continue to use the `github-auth` but switch to matrix based authorisation which allows ACL to be set for an org, team in an org or a user. 

In our case we can create a team in `fabric8io` say ~~`jenkins-build`~~ `ci-ops` (feel free to suggest a better name) and grant them the right it kill/start a build so that any member in that team. This also reduces the maintenance as any admin github org can grand this privilege to any user and when user is removed from the github org, they automatically lose their rights on Jenkins as well. 

The current jenkins admins can either be mapped into a github org team `ci-admins` as well so that Jenkins config need not be changed.

**Comment by chmouel** [comment] 2018-01-18 13:59
nice solution, i would better use another name tho like `fabric8-operators` since we may want to use it for something else in the future,

Next step would be to describe this on the ML i.e: we are going to have a team of people who are going to be allowed to kill any jobs and we would need to have the name of 2 ppl on each fabric8 team where we would add it in there.

thanks,

**Comment by rupalibehera** [comment] 2018-01-18 14:02
@sthaha , Nice solution if this works than it would be really great. Thanks for the investigation :) :+1:

**Comment by sthaha** [comment] 2018-01-19 01:52
@chmouel since the org is already fabric8io we don't want to repeat `fabric8-` in the team as well. How about `ci-ops`? so that it would read in jenkins config as `fabric8io*ci-ops`. Similarly there would be `ci-admins` akin to jenkins administrators the members of which will be our current list of admins.

**Comment by chmouel** [comment] 2018-01-19 05:44
Sounds good to me!

**Comment by chmouel** [comment] 2018-01-23 12:17
+Let's document this

**Comment by jaseemabid** [comment] 2018-01-23 12:19
@corinnekrych Can you comment your issue here?

**Comment by corinnekrych** [comment] 2018-01-23 12:29
@jaseemabid although I've logged in using my gh account, I can't trigger a build on PR branches (I used to be able to). see:
https://www.dropbox.com/s/3tgpiwkkc7px49p/Screenshot%202018-01-23%2013.27.37.png?dl=0
What should we do to gain ACL for triggering new build?

**Comment by sthaha** [comment] 2018-01-24 12:14
### Status update

The change has been implemented and is documented [here](https://github.com/fabric8io/fabric8-build-team/wiki/Jenkins-github-auth)

**Comment by jaseemabid** [comment] 2018-01-29 09:52
@sthaha I am unable to update the configuration of jobs from the UI now. I don't see a  save option anywhere.

**Comment by pradeepto** [comment] 2018-12-21 05:49
Closing as obsolete.

**Closed as completed by pradeepto** 2018-12-21 05:49 UTC
