### ISSUE TITLE
Jenkins master reboot and slave reconnect issue

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#17] opened 2018-01-08 15:56 UTC
The Jenkins master pod reboots whenever there are multiple jobs running(more than 4), after the reboot it continues to run all the previous on going job but it disconnects to the slave and later on not able to connect it back.

Need to do a bit of research for the same, we had some discussion about the kubernetes plugin can fix this and we did upgraded the plugin, check if this is still related.

**Comment by jaseemabid** [comment] 2018-01-24 06:17
@rupalibehera Please update the FAQ if you make any progress. https://github.com/fabric8io/fabric8-build-team/wiki/FAQ#i-get-the-error-jenkins-doesnt-have-label-whatever

**Comment by rupalibehera** [comment] 2018-01-29 12:01
I have observed after the reboot of the master the slaves for the ongoing jobs go to error state and maybe hence they are not able to connect back.

**Comment by rupalibehera** [comment] 2018-01-31 10:10
Observing issues like this on some of the PR pipeline too 
`node:7655) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Cannot contact jenkins-slave-h2b0q-1flqs: java.io.IOException: remote file operation failed: /home/jenkins/workspace/-ui_fabric8-planner_PR-2422-V4PPEPQFWZ6M2BXM6CBOKUC7GNQLRGXXTXIATGFVE7OO7POXAQ3Q@2 at hudson.remoting.Channel@6e684011:Channel to /10.12.8.105: hudson.remoting.ChannelClosedException: Remote call on Channel to /10.12.8.105 failed. The channel is closing down or has closed down, `
Noting it here for the record.

**Comment by rupalibehera** [comment] 2018-01-31 10:13
Added a logger to check the logs of kubernetes plugin while it spins up the slave pods https://jenkins.cd.test.fabric8.io/log/investigate%20slave%20reconnect%20failures/ I could find such logs `Total container cap of 5 reached, not provisioning: 10 running or errored in namespace cd` and when logged in to GKE found that the slaves were in error state

**Comment by jaseemabid** [comment] 2018-03-05 18:37
@rupalibehera I just noticed the same issue again on the newly provisioned 2a cluster and it looks worse than usual. Subsequent builds are going into the same state. Did you come across any useful workarounds, hints or solutions when you were looking into this? 

AFAIK, its getting stuck in this [loop](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesLauncher.java#L118) in the kubernetes-plugin and never recovering in a clean slate. 

@pradeepto we should probably prioritize this because this can be an arbitrarily long delay and its happening quite frequently now.

**Comment by jaseemabid** [comment] 2018-03-12 09:49
I've been repeatedly building maven-builder on test.cd.fabric8.io for a PR and about 10-12 of the builds went green before it got stuck again with `All nodes of label ‘clientsmaven_builder_12’ are offline`. We've seen this on every environment so far and is probably worth a SEV1 now. 

https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8io-images%2Fmaven-builder/detail/PR-37/12/pipeline/

**Comment by jaseemabid** [comment] 2018-03-13 11:36
@rupalibehera Do you think https://github.com/jenkinsci/kubernetes-plugin/pull/256 could be the root cause? The description seems to suggest it. We are currently using version 1.1, and this fix went into 1.3.2. Do you think we could update this plugin and give this a try?

**Comment by jaseemabid** [comment] 2018-03-15 08:31
Note to self, this might be relevant as well. 

```
Total container cap of 3 reached, not provisioning: 3 running or errored in namespace cd
Mar 15, 2018 8:11:51 AM INFO okhttp3.internal.platform.Platform log
```

**Comment by piyush-garg** [comment] 2018-12-21 05:53
we are not seeing this issue more now and also we have emoved content-repo. Closing this

**Closed as completed by piyush-garg** 2018-12-21 05:53 UTC
